<?xml version="1.0" encoding="utf-8"?><Database Name="2324_1A_LoginSample" Class="LoginSampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-E6RG946U;Initial Catalog=2324_1A_LoginSample;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="_2324_2Y_2A_IntegProg_LoginSampleLINQ.Properties.Settings" SettingsPropertyName="_2324_1A_LoginSampleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LoginUsers" Member="LoginUsers">
    <Type Name="LoginUser">
      <Column Name="LoginID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="LoginUser_Log" Member="Logs" ThisKey="LoginID" OtherKey="LoginID" Type="Log" />
    </Type>
  </Table>
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log">
      <Column Name="LogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoginID" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LoginUser_Log" Member="LoginUser" ThisKey="LoginID" OtherKey="LoginID" Type="LoginUser" IsForeignKey="true" />
    </Type>
  </Table>
</Database>